# Matrix Decomposition

In [1]:
import numpy as np
import scipy.linalg as sci_alg

## LU Decomposition with Partial Pivoting

In [2]:
# define a square matrix
A = np.array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A, '\n')

# factorize
P, L, U = sci_alg.lu(A)
print(P, '\n')
print(L, '\n')
print(U, '\n')

# reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]] 

[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]] 

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## QR Decomposition

In [3]:
# define rectangular matrix
A = np.array([
[1, 2],
[3, 4],
[5, 6]])
print(A, '\n')

# factorize
Q, R = np.linalg.qr(A, 'complete')
print(Q, '\n')
print(R, '\n')

# reconstruct
B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]] 

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]] 

[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]] 

[[1. 2.]
 [3. 4.]
 [5. 6.]]


## Cholesky Decomposition

In [4]:
# define symmetrical matrix
A = np.array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])
print(A)

# factorize
L = np.linalg.cholesky(A)
print(L)

# reconstruct
B = L.dot(L.T)

[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
